const createUserCommand =
    "CREATE TABLE IF NOT EXISTS User (id    INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, email TEXT    UNIQUE ON CONFLICT FAIL NOT NULL);";
const createNoteCommand =
    "CREATE TABLE IF NOT EXISTS Note (id    INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, user_id INTEGER REFERENCES User (id) NOT NULL,text  TEXT);";
