// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcyx83_PNa7Xp6k8V2NN0bHed8LriweeI',
    appId: '1:376697453835:web:712b1dac6d568118f2360e',
    messagingSenderId: '376697453835',
    projectId: 'gman-demo-app',
    authDomain: 'gman-demo-app.firebaseapp.com',
    storageBucket: 'gman-demo-app.appspot.com',
    measurementId: 'G-8G5H391M7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXyKn4uHAa6l3f6odRgMSqleoR7xbc25Q',
    appId: '1:376697453835:android:7fef25fb67dec004f2360e',
    messagingSenderId: '376697453835',
    projectId: 'gman-demo-app',
    storageBucket: 'gman-demo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvEgC6a65X00eEcYA2APXwSKbt8C5bBmU',
    appId: '1:376697453835:ios:b88c9a60cc0723d7f2360e',
    messagingSenderId: '376697453835',
    projectId: 'gman-demo-app',
    storageBucket: 'gman-demo-app.appspot.com',
    iosBundleId: 'com.example.flutterdemoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvEgC6a65X00eEcYA2APXwSKbt8C5bBmU',
    appId: '1:376697453835:ios:4e374fe879133859f2360e',
    messagingSenderId: '376697453835',
    projectId: 'gman-demo-app',
    storageBucket: 'gman-demo-app.appspot.com',
    iosBundleId: 'com.example.flutterdemoapp.RunnerTests',
  );
}
